export const HY = {
  patients: "Պացիենտներ",
  investigations: "Հետազոտություններ",
  profile: "Պրոֆիլ",
  searchPatient: "Ընդլայնված որոնում",
  loadFailed: "Պացիենտների ցանկը բեռնել չհաջողվեց",
  noPatients: "Պացիենտներ չեն գտնվել",
  loadMore: "Ավելին",
  labTitle: "Լաբորատոր հետազոտություններ",
  labFailed: "Հետազոտությունները բեռնել չհաջողվեց",
  noLabs: "Հետազոտություններ չկան",
  logout: "Դուրս գալ",
  accessDenied: "Այս բաժինը հասանելի չէ",
  user: "Օգտատեր",
  patient: "Պացիենտ",
  back: "Հետ",
  demographic: "Դեմոգրաֆիկ տվյալներ",
  inrNorm: "INR նորմա",
  inrNormScale: "INR նորմայի սանդղակ",
  editInrNorm: "Փոփոխել INR նորման",
  inrResults: "INR արդյունքներ",
  inrHistory: "INR արդյունքներ",
  newInr: "Նոր INR",
  newInrResult: "Նոր INR արդյունք",
  enterInrResults: "Մուտքագրեք հետազոտության արդյունքները",
  selectExamDate: "Ընտրել հետազոտության ամսաթիվ",
  enterInrValue: "Մուտքագրել INR արդյունքը",
  placeOfSubmission: "Հանձման վայրը",
  placePlaceholder: "օր․ ք․Երևան",
  scanDocument: "Սկանավորել փաստաթուղթը",
  scanHint:
    "Ուղղեք տեսախցիկը թերթիկին՝ ամսաթիվը և INR-ը ավտոմատ լրացնելու համար",
  scanAiming: "Պահեք թերթիկը շրջանակի մեջ...",
  scanUseResult: "Օգտագործել",
  scanPermissionNeeded:
    "Սկանավորելու համար անհրաժեշտ է ֆոտոխցիկի թույլտվություն",
  torch: "Լապտեր",
  scanPartial: "Լրացվեց միայն մի մասը, մնացածը լրացրեք ձեռքով։",
  scanUnsupported: "Այս սարքը չի աջակցում սկանավորումը",
  cameraPermissionDenied:
    "Ֆոտոխցիկի թույլտվությունը մերժված է։ Միացրեք այն սարքի կարգավորումներից։",
  attachDocuments: "Կցել փաստաթղթեր",
  uploadFile: "Ներբեռնել ֆայլ",
  uploadHint: "PDF, JPG, PNG (max 10MB)",
  previousResults: "Նախորդ արդյունքները",
  seeMore: "Տեսնել ավելին",
  enterInr: "Մուտքագրեք INR",
  currentInr: "Ընթացիկ INR",
  ttr: "TTR",
  dailyDose: "Օրվա դեղաչափ",
  nextTest: "Հաջորդ թեստ",
  notScheduled: "Նշանակված չէ",
  advice: "Խորհուրդներ",
  addAdvice: "Ավելացնել խորհուրդներ",
  addNewAdvice: "Ավելացնել նոր խորհուրդ",
  actualAdvice: "Ակտուալ խորհուրդներ",
  previousAdvice: "Նախորդ խորհուրդներ",
  noSavedAdvice: "Պահպանված խորհուրդներ չկան",
  adviceActualHint:
    "Վերջին ավելացված խորհուրդները ավտոմատ հայտնվում են ակտուալ խորհուրդների բաժնում",
  writeAdvice: "Գրել խորհուրդը",
  selectDateLabel: "Նշել ամսաթիվը",
  lastUpdate: "Վերջին թարմացում՝",
  backToMain: "Վերադառնալ գլխավոր էջ",
  complications: "Բարդություններ",
  addComplication: "Ավելացնել բարդություններ",
  addNewComplication: "Ավելացնել բարդություն",
  addAnotherComplication: "Ավելացնել նոր բարդություն",
  editComplications: "Փոփոխել բարդությունները",
  noSavedComplications: "Պահպանված բարդություններ չկան",
  complicationHint: "Ընտրեք կամ գրեք բարդություն",
  selectComplicationLabel: "Ընտրել բարդությունը",
  selectFromSuggested: "Ընտրել առաջարկված տարբերակներից",
  writeNotes: "Կատարել նշումներ",
  writePlaceholder: "Գրել . . . . . . . .",
  datePlaceholder: "02.09.98",
  calendar: "Օրացույց",
  dosage: "Դեղաչափ",
  save: "Պահպանել",
  cancel: "Չեղարկել",
  confirm: "Հաստատել",
  date: "Ամսաթիվ",
  months: [
    "Հունվար",
    "Փետրվար",
    "Մարտ",
    "Ապրիլ",
    "Մայիս",
    "Հունիս",
    "Հուլիս",
    "Օգոստոս",
    "Սեպտեմբեր",
    "Հոկտեմբեր",
    "Նոյեմբեր",
    "Դեկտեմբեր",
  ],
  /** Monday first, used by the month grid on the calendar screen. */
  weekdaysShort: ["Երկ", "Երք", "Չրք", "Հնգ", "Ուր", "Շբթ", "Կիր"],
  /** Sunday first, used by the date picker. */
  weekdaysNarrow: ["Կ", "Ե", "Ե", "Չ", "Հ", "Ու", "Շ"],
  comment: "Մեկնաբանություն",
  actual: "Ակտուալ",
  active: "Ակտիվ",
  notes: "Նշումներ",
  selectComplication: "Ընտրել բարդություն",
  normStart: "Նորմա սկիզբ",
  normEnd: "Նորմա վերջ",
  doseMg: "Դեղաչափ (մգ)",
  noAdvice: "Խորհուրդներ չկան",
  noComplications: "Բարդություններ չկան",
  noInrResults: "Արդյունքներ չկան",
  saved: "Պահպանվեց",
  complicationsSavedSuccess: "Բարդությունները հաջողությամբ պահպանվեցին",
  adviceSavedSuccess: "Խորհուրդները հաջողությամբ պահպանվեցին",
  error: "Սխալ",
  comingSoon: "Շուտով հասանելի կլինի",
  calendarLocalNote:
    "Օրացույցը աշխատում է տեղային տվյալներով՝ ինչպես desktop տարբերակում։",
  doctor: "Բժիշկ",
  attendingDoctor: "Վ․Բժիշկ",
  genderAge: "Սեռ / Տարիք",
  address: "Հասցե",
  idLabel: "ID",
  years: "տարեկան",
  brand: "ՆՄԲԿ",
  notifications: "Ծանուցումներ",
  messages: "Նամակներ",
  noMessages: "Նամակներ չկան",
  writeMessage: "Գրել հաղորդագրություն...",
  attach: "Կցել ֆայլ",
  send: "Ուղարկել",
  recordVoice: "Ձայնագրել",
  recording: "Ձայնագրվում է...",
  today: "ԱՅՍՕՐ",
  fileTooLarge: "Ֆայլը չպետք է գերազանցի 10ՄԲ",
  fileTypeNotAllowed:
    "Կարող եք ուղարկել PDF, նկար, աուդիո կամ office փաստաթուղթ",
  micPermissionDenied: "Միկրոֆոնի թույլտվությունը մերժված է",
  recordingFailed: "Ձայնագրել չհաջողվեց",
  sendMessageFailed: "Նամակն ուղարկել չհաջողվեց",
  chatLoadFailed: "Նամակները բեռնել չհաջողվեց",
  readAllChatFailed: "Նամակները կարդացված նշել չհաջողվեց",
  unread: "Չկարդացված",
  read: "Կարդացված",
  readAll: "Կարդալ բոլորը",
  noNotifications: "Ծանուցումներ չկան",
  deleteNotificationConfirm: "Հեռացնե՞լ այս ծանուցումը",
  invalidInr: "Խնդրում ենք մուտքագրել վավեր INR արժեք",
  invalidNorm: "Խնդրում ենք մուտքագրել վավեր նորմա",
  requiredField: "Դաշտը պարտադիր է",
  invalidNumber: "Մուտքագրեք թիվ",
  normOrder: "Նորմայի սկիզբը պետք է փոքր լինի վերջից",
  invalidDose: "Խնդրում ենք մուտքագրել վավեր դեղաչափ",
  inRange: "Նորմայի մեջ",
  outOfRange: "Նորմայից դուրս",
  region: "Մարզ",
  city: "Քաղաք",
  select: "Ընտրել",
  add: "Ավելացնել",
  edit: "Խմբագրել",
  delete: "Հեռացնել",
  note: "Նշում",
  enterNote: "Մուտքագրել Նշում",
  adviceSingle: "Խորհուրդ",
  requiredDate: "Խնդրում ենք մուտքագրել ամսաթիվ",
  dateNotBeforeToday: "Ամսաթիվը չի կարող լինել այսօրվանից առաջ",
  requiredInrValue: "Խնդրում ենք մուտքագրել INR արժեքը",
  requiredAdvice: "Խնդրում ենք մուտքագրել Խորհուրդ",
  requiredNote: "Խնդրում ենք մուտքագրել Նշում",
  requiredComplication: "Խնդրում ենք ընտրել բարդություն",
  patientNotFound: "Պացիենտը գտնված չէ",
  deleteInrConfirm: "Հեռացնե՞լ այս INR արդյունքը",
  selectAdvice: "Ընտրեք համապատասխան խորհուրդները",
  selectComplications: "Ընտրեք համապատասխան բարդությունները",
  enterNormRange: "Մուտքագրեք INR նորմայի սահմանները",
  allInrResults: "INR արդյունքների պատմություն",
  latestInrResult: "INR վերջին արդյունքը",
  inrAddedSuccess: "INR արդյունքը հաջողությամբ հաստատվեց",
  inrDeletedSuccess: "INR արդյունքը հաջողությամբ հեռացվեց",
  ok: "Լավ",
  dosageCalendar: "Դեղաչափերի օրացույց",
  prescribeDosage: "Դեղաչափի նշանակում",
  prescribeDosageHint:
    "Ընտրեք օր, սահմանեք դեղաչափի ցիկլ կամ նշանակեք հաջորդ թեստի օրը",
  selectDateForDoseOrTest:
    "Ընտրեք ամսաթիվը դեղաչափ կամ հաջորդ թեստի օր նշանակելու համար",
  nextTestHint: "Ընտրեք ամսաթիվը հաջորդ INR թեստի համար",
  dailyDoseHint: "Ընտրեք ամսաթիվը օրական դեղաչափ նշանակելու համար",
  selectOrCreateCycle: "Ընտրեք կամ ստեղծեք դեղաչափի ցիկլ",
  selectCycle: "Ընտրել ցիկլ",
  createCycle: "Ավելացնել",
  createDosageCycle: "Ավելացնել դեղաչափ",
  savedCycles: "Պահպանված ցիկլեր",
  savedCyclesHint: "Ընտրեք պահպանված դեղաչափի ցիկլ արագ կիրառելու համար",
  noSavedCycles: "Պահպանված ցիկլեր չկան",
  duration: "Տևողություն",
  createdOn: "Ստեղծվել է",
  daysUnit: "օր",
  dailyWarfarinDose: "Օրական Warfarin Դեղաչափ",
  selectOrEnterDailyDose: "Ընտրեք կամ մուտքագրեք օրական դեղաչափը",
  nextTestDate: "Հաջորդ Թեստի Ամսաթիվ",
  setAsNextTest: "Սահմանել որպես հաջորդ թեստ",
  setAsNextTestDone: "Սահմանված է որպես հաջորդ թեստ",
  markAsNextInrTest: "Նշեք այս օրը որպես հաջորդ INR թեստի ամսաթիվ",
  doseAndNextTest: "Դեղաչափ & Հաջորդ թեստ",
  mg: "մգ",
  selectDateRangeHint:
    "Սահեցրեք մատը միջակայք ընտրելու համար։ Սեղմեք օրը՝ ցիկլին ավելացնելու կամ հեռացնելու համար։",
  defaultDoseHint:
    "Բոլոր դեղաչափերը սկզբնապես սահմանված են 2.00 մգ: Կարգավորեք յուրաքանչյուր օրը՝ ըստ անհրաժեշտության:",
  selectedRange: "Ընտրված միջակայք՝",
  saveCycle: "Ստեղծել ցիկլ",
  applyDosage: "Կիրառել դեղաչափը",
  enterCycleName: "Մուտքագրեք ցիկլի անունը",
  cycleNamePlaceholder: "օր.՝ Հնգօրյա ցիկլ",
  activeDosageCycle: "Ակտիվ դեղաչափի ցիկլ",
  cycleApplied: "Ցիկլը կիրառված է՝",
  editCycle: "Փոփոխել ցիկլը",
  removeCycle: "Հեռացնել ցիկլը",
  removeCurrentCycle: "Հեռացնել ընթացիկ ցիկլը",
  removeCurrentCycleConfirm: "Հեռացնե՞լ ընթացիկ դեղաչափի ցիկլը:",
  removeCurrentCycleHint:
    "Սա կհեռացնի ցիկլի միջոցով կիրառված բոլոր դեղաչափերը:",
  deleteCycle: "Ջնջել ցիկլը",
  deleteCycleConfirm: "Վստա՞հ եք, որ ցանկանում եք ջնջել դեղաչափի ցիկլը:",
  deleteCycleHint: "Ջնջելու դեպքում ցիկլը վերականգնել հնարավոր չէ:",
  inrTestDay: "INR թեստի հանձման օր",
  dayN: "Օր",
  weekdaysLong: [
    "Կիրակի",
    "Երկուշաբթի",
    "Երեքշաբթի",
    "Չորեքշաբթի",
    "Հինգշաբթի",
    "Ուրբաթ",
    "Շաբաթ",
  ],
} as const;
