export const HY = {
  patients: "Պացիենտներ",
  investigations: "Հետազոտություններ",
  profile: "Պրոֆիլ",
  searchPatient: "Որոնել պացիենտ...",
  loadFailed: "Պացիենտների ցանկը բեռնել չհաջողվեց",
  noPatients: "Պացիենտներ չեն գտնվել",
  loadMore: "Ավելին",
  labTitle: "Լաբորատոր հետազոտություններ",
  labFailed: "Հետազոտությունները բեռնել չհաջողվեց",
  noLabs: "Հետազոտություններ չկան",
  logout: "Դուրս գալ",
  user: "Օգտատեր",
  patient: "Պացիենտ",
  back: "Հետ",
  demographic: "Դեմոգրաֆիկ տվյալներ",
  inrNorm: "INR նորմա",
  inrNormScale: "INR նորմայի սանդղակ",
  editInrNorm: "Փոփոխել INR նորման",
  inrResults: "INR արդյունքներ",
  inrHistory: "INR պատմություն",
  newInr: "Նոր INR",
  newInrResult: "Նոր INR արդյունք",
  enterInrResults: "Մուտքագրեք հետազոտության արդյունքները",
  selectExamDate: "Ընտրել հետազոտության ամսաթիվ",
  enterInrValue: "Մուտքագրել INR արդյունքը",
  placeOfSubmission: "Հանձման վայրը",
  placePlaceholder: "օր․ ք․Երևան",
  attachDocuments: "Կցել փաստաթղթեր",
  uploadFile: "Ներբեռնել ֆայլ",
  uploadHint: "PDF, JPG, PNG (max 10MB)",
  previousResults: "Նախորդ արդյունքները",
  seeMore: "Տեսնել ավելին",
  enterInr: "Մուտքագրեք INR",
  currentInr: "Ընթացիկ INR",
  ttr: "TTR",
  dailyDose: "Օրվա դեղաչափ",
  nextTest: "Հաջորդ թեստ",
  notScheduled: "Նշանակված չէ",
  advice: "Խորհուրդներ",
  addAdvice: "Ավելացնել խորհուրդներ",
  complications: "Բարդություններ",
  addComplication: "Ավելացնել բարդություններ",
  calendar: "Օրացույց",
  dosage: "Դեղաչափ",
  save: "Պահպանել",
  cancel: "Չեղարկել",
  date: "Ամսաթիվ",
  comment: "Մեկնաբանություն",
  actual: "Ակտուալ",
  notes: "Նշումներ",
  selectComplication: "Ընտրել բարդություն",
  normStart: "Նորմա սկիզբ",
  normEnd: "Նորմա վերջ",
  doseMg: "Դեղաչափ (մգ)",
  noAdvice: "Խորհուրդներ չկան",
  noComplications: "Բարդություններ չկան",
  noInrResults: "Արդյունքներ չկան",
  saved: "Պահպանվեց",
  comingSoon: "Շուտով հասանելի կլինի",
  calendarLocalNote: "Օրացույցը աշխատում է տեղային տվյալներով՝ ինչպես desktop տարբերակում։",
  doctor: "Բժիշկ",
  years: "տարեկան",
  brand: "ՆՄԲԿ",
  invalidInr: "Խնդրում ենք մուտքագրել վավեր INR արժեք",
  invalidNorm: "Խնդրում ենք մուտքագրել վավեր նորմա",
  inRange: "Նորմայի մեջ",
  outOfRange: "Նորմայից դուրս",
} as const;
